/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.alexprom.uppg_reports;

import com.alexprom.entities.process.VactUPPG;
import com.microsoft.sqlserver.jdbc.SQLServerDriver;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.persistence.EntityManager;
import javax.persistence.Persistence;
import javax.persistence.Query;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;
import org.openide.util.Exceptions;

/**
 *
 * @author Lenovo
 */
public class UPPG_ShiftReport extends javax.swing.JPanel {

    private String reportSource = "./report_templates/actUPPG.jrxml";
    //private String reportDest = "./report_results/simple.html";
    private Map<String, Object> params;
    
    public UPPG_ShiftReport() {
        initComponents();
        
        this.params = new HashMap<>();
        try{
            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            params.put("actID", new Long(3));
            //params.put("SUBREPORT_DIR", "./report_templates/");
            EntityManager em = Persistence.createEntityManagerFactory("ProcessDictionaryPU").createEntityManager();
            
            //JasperViewer.viewReport(jasperPrint);
            try {
                JasperPrint jasperPrint;
                jasperPrint = JasperFillManager.fillReport(jasperReport, params, getConnection());
                //JasperExportManager.exportReportToHtmlFile(jasperPrint, reportDest);
                JasperViewer jasperView = new JasperViewer(jasperPrint);
                jasperView.show();
                //jasperView.setVisible(true);
                //this.add(viewer);
            } catch (Exception ex) {
                Exceptions.printStackTrace(ex);
            }
            
            
        }catch (JRException ex){
            ex.printStackTrace();
        }
    
    }
    
    private static Connection getConnection() throws Exception {
        DriverManager.registerDriver(new SQLServerDriver());
        Connection conn = DriverManager.getConnection("jdbc:sqlserver://176.105.202.29:1433;databaseName=Alexprom_ASUTP", "roman", "roman");
        return conn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
